### ISSUE TITLE
[Feature Request] Flatpak release?

### ISSUE THREAD

**Issue by fernvenue** [Vito0912/abs_flutter#137]
**Feature Request**

**Problem Description**
I just found out that in the releases, there are only AppImage and binary, and there is neither flatpak nor is it published on flathub.org.

**Proposed Solution**
Provide flatpak and put it to flathub.org maybe?

**Considered Alternatives**
It is also great to provide only flatpak without releasing it to flathub.org.

**Platform-Specific Requirements (if any)**
Linux :)

**Comment by Vito0912** [comment]
Hello,
currently development is a little bit slow.
I am no Linux Dev at all and sadly did not accomplish to create a flatpak. Help is appreciated in that matter.
The arch release for example is also not managed by me.
I am open to implement it, but I am missing the knowledge to achieve this.

**Comment by fernvenue** [comment]
Hi @Vito0912, thanks for your reply! I would like to know if you have a permissive attitude towards contributions related to Flatpak?

**Comment by Vito0912** [comment]
As mentioned in the previous comment, I am open to contributions. The only requirement is transparency (so everyone can see how it is built). However, as far as I know, Flatpak already requires this. Additionally, the process should be fully automated, or I would need co-access to whatever is being used (though automation is highly preferred).

**Comment by kurwjan** [comment]
I'll look into it.

**Comment by kurwjan** [comment]
I first tried it with snap, bc I needed fewer preparations for this (and the concepts of interfaces can be transferred to flatpak permissions).

It was a pain in the ass. I'll try now flathub but I don't have high hopes.

This is the snap manifest:
```yaml
name: buchable
version: 1.7.7
summary: Enjoy hearing self-hosted audiobooks.
description: testtesttesttestttest
website: https://github.com/Vito0912/abs_flutter
contact: fito0912@duck.com
source-code: https://github.com/Vito0912/abs_flutter
icon: snap/gui/buchable.png

confinement: strict
base: core22
grade: stable
license: BSD-3-Clause

architectures:
  - build-on: amd64

layout:
  /usr/lib/libmpv.so:
    symlink: $SNAP/usr/lib/x86_64-linux-gnu/libmpv.so # --> maybe needed for flatpak

slots:
  dbus-buchable:
    interface: dbus
    bus: session
    name: io.github.vito0912.abs_flutter
  mpris: # --> need flatpak equivalent
    interface: mpris
    name: ABSPlayback

apps:
  buchable:
    command: abs_flutter
    extensions: [gnome]
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - network
      - network-manager-observe # --> ConnectivityPlus tries to reach "NetworkManager"
      - audio-playback # --> doesn't quite work?
      - pulseaudio
      - password-manager-service # --> flatpak equivalent: --talk-name=org.freedesktop.secrets
    slots:
      - dbus-buchable
      - mpris
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/blas:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/lapack:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/caca:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/vdpau:$SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/mfx # --> probably also need to passthrough LD_LIBRARY_PATH in flatpak

parts:
  buchable:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    build-packages:
      - libsecret-1-dev # --> needed for flatpak?
      - libjsoncpp-dev
    stage-packages:
      - libsecret-1-0
      - libmpv-dev
      - ca-certificates
```

There are errors/warnings like these:

_Internet does work, I can login but on play this shit comes._
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

```

```
flutter: Something is wrong. Please use positionStream later
```

```
flutter: media_kit: WARNING: package:media_kit_native_event_loop not found.
```

And some ALSA errors.
